env: sc2

env_args:
  continuing_episode: False
  difficulty: "7"
  game_version: null
<<<<<<< HEAD
  map_name: "5m_vs_6m_new03"
=======
  map_name: "3s_vs_5z_new01"
>>>>>>> 2ac4495 (日期0721 修改了局面三&局面四的lamda和reward 使其得以适应不同视距的智能体 同时做了数据清洗 去除了具有敌方智能体的数据)
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: ""
  replay_prefix: ""
  state_last_action: True
  state_timestep_number: False
  step_mul: 8
  seed: null
  heuristic_ai: False
  heuristic_rest: False
  debug: False
 
test_greedy: True
test_nepisode: 8
test_interval: 100
log_interval: 100
runner_log_interval: 100
learner_log_interval: 100
t_max: 10000