# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc201" # Environment name
algs: 'iql'
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 5 # Number of episodes to test for
test_interval: 10 # Test after {} timesteps have passed 
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 50 # Log summary of stats after every {} timesteps 
runner_log_interval: 50 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 50 # Log training stats every {} timesteps
t_max: 150 # Stop running after this many timesteps 
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: False # If true we won't keep all of the replay buffer in vram

<<<<<<< HEAD
# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: true # Save the models to disk
save_model_interval: 500 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
# checkpoint_path: "/home/data_0/ysq_23/results/models/iql__2024-07-08_23-38-40"
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
# save_replay: true
=======
# --- Logging options --- train --- 
use_tensorboard: True # Log results to tensorboard
save_model: true # Save the models to disk
save_model_interval: 5000 # Save models after this many timesteps
checkpoint_path: "" # Load a checkpoint from this path
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
>>>>>>> 2ac4495 (日期0721 修改了局面三&局面四的lamda和reward 使其得以适应不同视距的智能体 同时做了数据清洗 去除了具有敌方智能体的数据)
local_results_path: "results" # Path for local results

# --- Logging options --- replay --- 
# use_tensorboard: False # Log results to tensorboard
# save_model: False # Save the models to disk
# save_model_interval: 5000 # Save models after this many timesteps
# checkpoint_path: "/home/data_0/ysq_23/results/models/iql__2024-07-20_20-42-19" # model --- path
# evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
# load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
# save_replay: True # Saving the replay of the model loaded from checkpoint_path
# local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 4 # Number of episodes to train on
buffer_size: 4 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"
